name: Update Mihomo

on:
  schedule:
    - cron: '0 0 1,15 * *'  # 每月1号和15号执行
  workflow_dispatch:  # 允许手动运行

jobs:
  download-latest-mihomo:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Get latest version tag from GitHub
        id: get_version
        shell: bash
        run: |
          LATEST=$(curl -s https://api.github.com/repos/MetaCubeX/mihomo/releases/latest | jq -r '.tag_name')
          echo "LATEST_TAG=$LATEST" >> $GITHUB_ENV
          echo "Latest Mihomo version: $LATEST"

      - name: Download and extract Mihomo (non-go version)
        shell: pwsh
        run: |
          $version = "${env:LATEST_TAG}"
          $url = "https://github.com/MetaCubeX/mihomo/releases/download/$version/mihomo-windows-amd64-compatible-$version.zip"
          Write-Host "Downloading from $url"

          Invoke-WebRequest -Uri $url -OutFile "mihomo.zip" -TimeoutSec 300
          Expand-Archive -Path "mihomo.zip" -DestinationPath . -Force
          Remove-Item "mihomo.zip"

          $exe = Get-ChildItem -Recurse -Filter "*mihomo*.exe" | Select-Object -First 1
          if ($exe) {
            Rename-Item -Path $exe.FullName -NewName "mihomo.exe" -Force
            Write-Host "mihomo.exe ready."
          } else {
            throw "mihomo.exe not found after extraction"
          }

      - name: Commit and push if updated
        shell: bash
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github
